### PR TITLE
fix: strip tmpDir from output dir

### LINKED ISSUE #107: [BUG] On Windows, tries to write to temp dir instead of output dir and fails
#### Describe the bug

On Windows, simple-scaffold writes the output to temp dir instead of output dir

#### How To Reproduce

Use github config file

   ```shell
   npx simple-scaffold -g o68x/my-simple-scaffolds -c scaffold.js -k duplicacy name -l debug
   ```

#### Expected behavior\*\*

Should write to the output dir (here the working dir)

#### Logs

[log.txt](https://github.com/user-attachments/files/17154510/log.txt)

#### Desktop

- OS:Windows
- OS Version: 10
- Node.js: 20.17.0
- Simple Scaffold Version 2.3.0

### PR DESCRIPTION
**Pull request by chenasraf**
Fixes #107 

- [ ] Solution verified (needs testing)

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -80,8 +80,20 @@ export async function getConfigFile(config: ScaffoldCmdConfig, tmpPath: string):
 }
 
 /** @internal */
-export async function parseConfigFile(config: ScaffoldCmdConfig, tmpPath: string): Promise<ScaffoldConfig> {
-  let output: ScaffoldConfig = { ...config, beforeWrite: undefined }
+export async function parseConfigFile(config: ScaffoldCmdConfig): Promise<ScaffoldConfig> {
+  let output: ScaffoldConfig = {
+    name: config.name,
+    templates: [],
```
Comment (swcarter007) [inline src/config.ts:86]: It appears this change may have broken the templates.  Previously, if a user defined a template, it would pass through with the parsed config, but afterward the templates is being reset to an empty array, so its not matching on any files.

Comment (chenasraf) [reply src/config.ts:86]: Just so I understand fully what you mean, when you say "user defined", do you mean via the CLI args, trying to add data to the template config?

Or the config itself loses the templates?

Comment (chenasraf) [reply src/config.ts:86]: Created a new issue to track this regression

https://github.com/chenasraf/simple-scaffold/issues/110

Let's continue communication there so it's easier to track
